services:
  - type: web
    name: invoice-api
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: invoice-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: invoice-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: invoice-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: invoice-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: invoice-db
          property: password
      - key: APP_ADMIN_PASSWORD
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: invoice-db
    plan: free