apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoice-api.fullname" . }}-secret
  labels:
    {{- include "invoice-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  APP_ADMIN_PASSWORD: {{ .Values.app.adminPassword | quote }}
  JWT_SECRET: {{ .Values.app.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
